import { type CarouselSlide } from '@pages/Main/components/Carousel';
import { CATEGORY_IDS } from '@constants/categoryData';
import SlideImage1 from '@assets/images/slide1.jpeg';
import SlideImage2 from '@assets/images/slide2.jpeg';
import SlideImage3 from '@assets/images/slide3.jpeg';
import SlideImage4 from '@assets/images/slide4.jpeg';

export const MOCK_SLIDES: CarouselSlide[] = [
  {
    id: 1,
    thumbnailUrl: SlideImage1,
  },
  {
    id: 2,
    thumbnailUrl: SlideImage2,
  },
  {
    id: 3,
    thumbnailUrl: SlideImage3,
  },
  {
    id: 4,
    thumbnailUrl: SlideImage4,
  },
];

export const MOCK_SERVICES = [
  {
    id: 302,
    name: '1인 가게를 위한 창업 브랜딩 전략 코칭',
    minPrice: 70000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9102,
    providerName: '조영순',
  },
  {
    id: 303,
    name: '초기 창업자를 위한 실행계획서 코칭',
    minPrice: 100000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9103,
    providerName: '박인서',
  },
  {
    id: 304,
    name: '동네 장사를 위한 간판/홍보전략 컨설팅',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9104,
    providerName: '이명호',
  },
  {
    id: 305,
    name: '시장 조사 및 유사 업종 비교 분석 자료 제공',
    minPrice: 35000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9105,
    providerName: '배현숙',
  },
  {
    id: 306,
    name: '사업 운영 중 문제 해결 사례 공유 및 조언',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9106,
    providerName: '김두식',
  },
  {
    id: 307,
    name: '퇴직자 창업 노하우 공유 세션',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.BUSINESS,
    thumbnailUrl: '',
    providerId: 9107,
    providerName: '황순자',
  },
  {
    id: 308,
    name: '개인 브랜딩 컨설팅 (포트폴리오 중심)',
    minPrice: 40000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9108,
    providerName: '한경자',
  },
  {
    id: 309,
    name: '경력 재설계를 위한 진로 상담',
    minPrice: 35000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9109,
    providerName: '정연희',
  },
  {
    id: 310,
    name: '시니어 창업 아이템 멘토링',
    minPrice: 50000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9110,
    providerName: '김대현',
  },
  {
    id: 311,
    name: '퇴직 후 커리어 설계 코칭',
    minPrice: 45000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9111,
    providerName: '장성희',
  },
  {
    id: 312,
    name: '자기소개서/경력기술서 첨삭',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9112,
    providerName: '이정숙',
  },
  {
    id: 313,
    name: '시니어 맞춤 강의 컨설팅',
    minPrice: 33000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9113,
    providerName: '문진우',
  },
  {
    id: 314,
    name: '중년 이후 삶의 방향 상담 (라이프 코칭)',
    minPrice: 40000,
    categoryId: CATEGORY_IDS.CONSULTING,
    thumbnailUrl: '',
    providerId: 9114,
    providerName: '윤현주',
  },
  {
    id: 315,
    name: '전통시장 SNS 홍보 컨설팅',
    minPrice: 40000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9115,
    providerName: '문지현',
  },
  {
    id: 316,
    name: '고령층 대상 맞춤 마케팅 자문',
    minPrice: 35000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9116,
    providerName: '장성우',
  },
  {
    id: 317,
    name: '작은 가게를 위한 리뷰 관리 대행',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9117,
    providerName: '하정희',
  },
  {
    id: 318,
    name: '블로그 콘텐츠 기획 및 작성',
    minPrice: 28000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9118,
    providerName: '유지선',
  },
  {
    id: 319,
    name: 'SNS 광고 문구 첨삭',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9119,
    providerName: '이용자',
  },
  {
    id: 320,
    name: '가게 전단지 문구 구성 컨설팅',
    minPrice: 27000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9120,
    providerName: '박미영',
  },
  {
    id: 321,
    name: '중장년 유튜버를 위한 콘텐츠 방향성 코칭',
    minPrice: 45000,
    categoryId: CATEGORY_IDS.MARKETING,
    thumbnailUrl: '',
    providerId: 9121,
    providerName: '김문철',
  },
  {
    id: 322,
    name: '웹 개발 산출물 리뷰 및 기술 문서 작성',
    minPrice: 10000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9122,
    providerName: '오철민',
  },
  {
    id: 323,
    name: '노코드로 만드는 개인 홈페이지',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9123,
    providerName: '고윤석',
  },
  {
    id: 324,
    name: '블로그에 기능 넣기 (지도, 예약 등)',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9124,
    providerName: '김남중',
  },
  {
    id: 325,
    name: '스프링 부트 클린 코드 리뷰',
    minPrice: 5000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9125,
    providerName: '장병수',
  },
  {
    id: 326,
    name: '간단한 웹 폼 제작 (신청, 예약)',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9126,
    providerName: '최창호',
  },
  {
    id: 327,
    name: '시니어 대상 IT 서비스 UX 피드백',
    minPrice: 32000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9127,
    providerName: '박연숙',
  },
  {
    id: 328,
    name: '웹사이트 배포 도와드립니다 (GitHub Pages 등)',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.DEVELOPMENT,
    thumbnailUrl: '',
    providerId: 9128,
    providerName: '윤성일',
  },
  {
    id: 329,
    name: '소규모 프로젝트 디자인 기획',
    minPrice: 35000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9129,
    providerName: '송경희',
  },
  {
    id: 330,
    name: '명함 디자인 및 인쇄 파일 제작',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9130,
    providerName: '김인자',
  },
  {
    id: 331,
    name: '전단지/배너 디자인',
    minPrice: 40000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9131,
    providerName: '정선주',
  },
  {
    id: 332,
    name: '가게 로고 간단 제작',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9132,
    providerName: '박화자',
  },
  {
    id: 333,
    name: 'SNS 카드뉴스 디자인',
    minPrice: 28000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9133,
    providerName: '이창숙',
  },
  {
    id: 334,
    name: '파워포인트 발표자료 디자인 개선',
    minPrice: 35000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9134,
    providerName: '윤광자',
  },
  {
    id: 335,
    name: '웹 디자인 피드백 및 개선안 제시',
    minPrice: 40000,
    categoryId: CATEGORY_IDS.DESIGN,
    thumbnailUrl: '',
    providerId: 9135,
    providerName: '한준희',
  },
  {
    id: 336,
    name: '전문 보고서/논문 교정',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9136,
    providerName: '이준열',
  },
  {
    id: 337,
    name: '자서전/회고록 글쓰기 도우미',
    minPrice: 45000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9137,
    providerName: '윤현숙',
  },
  {
    id: 338,
    name: '인터뷰 원고 정리 및 교정',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9138,
    providerName: '강미숙',
  },
  {
    id: 339,
    name: '중장년 수기 첨삭 및 구성 자문',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9139,
    providerName: '문석호',
  },
  {
    id: 340,
    name: '이력서/자기소개서 글쓰기 피드백',
    minPrice: 50000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9140,
    providerName: '김복선',
  },
  {
    id: 341,
    name: '고령층 자기 PR 글쓰기 코칭',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.WRITE,
    thumbnailUrl: '',
    providerId: 9141,
    providerName: '정명희',
  },
  {
    id: 342,
    name: '생활 서류 한영 번역',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.TRANSLATION,
    thumbnailUrl: '',
    providerId: 9142,
    providerName: '정광호',
  },
  {
    id: 343,
    name: '간단 이메일 번역 및 첨삭',
    minPrice: 5000,
    categoryId: CATEGORY_IDS.TRANSLATION,
    thumbnailUrl: '',
    providerId: 9143,
    providerName: '홍수자',
  },
  {
    id: 344,
    name: '관공서 서류 번역 도와드립니다',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.TRANSLATION,
    thumbnailUrl: '',
    providerId: 9144,
    providerName: '이상옥',
  },
  {
    id: 345,
    name: '여행자 일본 문장 교정',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.TRANSLATION,
    thumbnailUrl: '',
    providerId: 9145,
    providerName: '조남형',
  },
  {
    id: 346,
    name: '수기 영문 번역 첨삭',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.TRANSLATION,
    thumbnailUrl: '',
    providerId: 9146,
    providerName: '박은희',
  },
  {
    id: 347,
    name: '인터뷰 영상 클립 제작',
    minPrice: 100000,
    categoryId: CATEGORY_IDS.PHOTOGRAPH,
    thumbnailUrl: '',
    providerId: 9147,
    providerName: '최기환',
  },
  {
    id: 348,
    name: '가게용 제품 사진 촬영',
    minPrice: 50000,
    categoryId: CATEGORY_IDS.PHOTOGRAPH,
    thumbnailUrl: '',
    providerId: 9148,
    providerName: '정하영',
  },
  {
    id: 349,
    name: '영상 편집 도와드립니다 (간단 컷 편집)',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.PHOTOGRAPH,
    thumbnailUrl: '',
    providerId: 9149,
    providerName: '윤금자',
  },
  {
    id: 350,
    name: '가족사진 리터치 및 앨범 제작',
    minPrice: 70000,
    categoryId: CATEGORY_IDS.PHOTOGRAPH,
    thumbnailUrl: '',
    providerId: 9150,
    providerName: '남선화',
  },
  {
    id: 351,
    name: '인터뷰 자막 삽입 및 타이포 조정',
    minPrice: 60000,
    categoryId: CATEGORY_IDS.PHOTOGRAPH,
    thumbnailUrl: '',
    providerId: 9151,
    providerName: '문성기',
  },
  {
    id: 352,
    name: '초등학생 수학 개념 다시 잡기',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9152,
    providerName: '이영주',
  },
  {
    id: 353,
    name: '국어 글쓰기 첨삭 지도',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9153,
    providerName: '조은희',
  },
  {
    id: 354,
    name: '기초 한자 배우기',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9154,
    providerName: '이태순',
  },
  {
    id: 355,
    name: '시니어 스마트폰 사용법 교육',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9155,
    providerName: '김현수',
  },
  {
    id: 356,
    name: '부모님을 위한 줌(ZOOM) 사용 교육',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9156,
    providerName: '박진옥',
  },
  {
    id: 357,
    name: '글씨체 교정 수업 (펜글씨)',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.EDUCATION,
    thumbnailUrl: '',
    providerId: 9157,
    providerName: '황은희',
  },
  {
    id: 358,
    name: '따뜻한 감성이 담긴 캘리그라피',
    minPrice: 5000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9158,
    providerName: '이화자',
  },
  {
    id: 359,
    name: '손뜨개 소품 제작',
    minPrice: 15000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9159,
    providerName: '박수진',
  },
  {
    id: 360,
    name: '자수 소품 클래스',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9160,
    providerName: '김진숙',
  },
  {
    id: 361,
    name: '천연비누 만들기 키트 제작',
    minPrice: 10000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9161,
    providerName: '이종희',
  },
  {
    id: 362,
    name: '한지 공예 클래스',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9162,
    providerName: '정문자',
  },
  {
    id: 363,
    name: '리본아트 및 포장 디자인',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.CRAFT,
    thumbnailUrl: '',
    providerId: 9163,
    providerName: '조선미',
  },
  {
    id: 364,
    name: '중장년을 위한 합창 수업',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9164,
    providerName: '민경자',
  },
  {
    id: 365,
    name: '시 창작 수업',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9165,
    providerName: '장은철',
  },
  {
    id: 366,
    name: '소규모 기타 교습 (초급)',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9166,
    providerName: '오정숙',
  },
  {
    id: 367,
    name: '정리수납 클래스 (라이프 코칭 포함)',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9167,
    providerName: '이선자',
  },
  {
    id: 368,
    name: '가계부 쓰는 법, 재무 취미 수업',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9168,
    providerName: '김기분',
  },
  {
    id: 369,
    name: '시니어 유튜버를 위한 콘텐츠 만들기 워크숍',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.HOBBY,
    thumbnailUrl: '',
    providerId: 9169,
    providerName: '조희란',
  },
  {
    id: 370,
    name: '가정 내 안전 점검 체크리스트 컨설팅',
    minPrice: 20000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9170,
    providerName: '홍명자',
  },
  {
    id: 371,
    name: '혼자 사는 분들을 위한 식단 코칭',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9171,
    providerName: '장세진',
  },
  {
    id: 372,
    name: '고령자를 위한 집안 정리 서비스',
    minPrice: 30000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9172,
    providerName: '나미라',
  },
  {
    id: 373,
    name: '간단한 의류 수선 및 정리법 안내',
    minPrice: 25000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9173,
    providerName: '윤정아',
  },
  {
    id: 374,
    name: '집안 청소 동선 컨설팅 (요령 포함)',
    minPrice: 10000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9174,
    providerName: '김선례',
  },
  {
    id: 375,
    name: '1인 가구를 위한 생활 정리법 강의',
    minPrice: 10000,
    categoryId: CATEGORY_IDS.LIVING,
    thumbnailUrl: '',
    providerId: 9175,
    providerName: '오진숙',
  },
];
