export const SKILLS_BY_CATEGORY = {
  1: [
    { id: 1, name: '사업계획서 작성' },
    { id: 2, name: '시장조사' },
    { id: 3, name: '경영전략 수립' },
    { id: 4, name: '조직관리' },
    { id: 5, name: '프로젝트 관리' },
    { id: 6, name: 'SWOT 분석' },
    { id: 7, name: '재무계획' },
    { id: 8, name: '투자계획' },
    { id: 9, name: '리스크 관리' },
    { id: 10, name: '성과관리' },
    { id: 11, name: '비즈니스 모델 개발' },
    { id: 12, name: 'OKR/KPI 설계' },
    { id: 13, name: '경영진 보고서 작성' },
    { id: 14, name: '내부 프로세스 진단' },
    { id: 15, name: 'PMO 운영' },
  ],
  2: [
    { id: 16, name: '경영컨설팅' },
    { id: 17, name: '전략컨설팅' },
    { id: 18, name: '조직컨설팅' },
    { id: 19, name: '인사컨설팅' },
    { id: 20, name: 'IT컨설팅' },
    { id: 21, name: '창업멘토링' },
    { id: 22, name: '취업멘토링' },
    { id: 23, name: '커리어 코칭' },
    { id: 24, name: '라이프 코칭' },
    { id: 25, name: '비즈니스 코칭' },
    { id: 26, name: '세무/회계 컨설팅' },
    { id: 27, name: '브랜드 컨설팅' },
    { id: 28, name: '디지털 전환(DX) 컨설팅' },
    { id: 29, name: '프로세스 개선 멘토링' },
    { id: 30, name: '해외 진출 전략' },
  ],
  3: [
    { id: 31, name: '디지털 마케팅' },
    { id: 32, name: 'SNS 마케팅' },
    { id: 33, name: '콘텐츠 마케팅' },
    { id: 34, name: '바이럴 마케팅' },
    { id: 35, name: 'SEO/SEM' },
    { id: 36, name: '브랜딩' },
    { id: 37, name: '광고기획' },
    { id: 38, name: 'PR' },
    { id: 39, name: '마케팅 분석' },
    { id: 40, name: '고객관리' },
    { id: 41, name: 'CRM 캠페인 운영' },
    { id: 42, name: '이메일 마케팅' },
    { id: 43, name: '인플루언서 마케팅' },
    { id: 44, name: '리타게팅 광고' },
    { id: 45, name: '마케팅 자동화' },
  ],
  4: [
    { id: 46, name: 'React' },
    { id: 47, name: 'Vue.js' },
    { id: 48, name: 'Angular' },
    { id: 49, name: 'Node.js' },
    { id: 50, name: 'Python' },
    { id: 51, name: 'Java' },
    { id: 52, name: 'Spring' },
    { id: 53, name: 'Django' },
    { id: 54, name: 'Flask' },
    { id: 55, name: 'Express.js' },
    { id: 56, name: 'MySQL' },
    { id: 57, name: 'PostgreSQL' },
    { id: 58, name: 'MongoDB' },
    { id: 59, name: 'AWS' },
    { id: 60, name: 'Docker' },
    { id: 61, name: 'Kubernetes' },
    { id: 62, name: 'Git' },
    { id: 63, name: 'JavaScript' },
    { id: 64, name: 'TypeScript' },
    { id: 65, name: 'Next.js' },
    { id: 66, name: 'NestJS' },
    { id: 67, name: 'GraphQL' },
    { id: 68, name: 'Firebase' },
    { id: 69, name: 'CI/CD 구축' },
    { id: 70, name: '웹 보안' },
    { id: 71, name: '모바일 앱 개발' },
  ],
  5: [
    { id: 72, name: 'Adobe Photoshop' },
    { id: 73, name: 'Adobe Illustrator' },
    { id: 74, name: 'Adobe InDesign' },
    { id: 75, name: 'Adobe XD' },
    { id: 76, name: 'Figma' },
    { id: 77, name: 'Sketch' },
    { id: 78, name: 'Canva' },
    { id: 79, name: 'Adobe After Effects' },
    { id: 80, name: 'Adobe Premiere Pro' },
    { id: 81, name: 'Blender' },
    { id: 82, name: 'Cinema 4D' },
    { id: 83, name: '3ds Max' },
    { id: 84, name: 'Maya' },
    { id: 85, name: 'AutoCAD' },
    { id: 86, name: 'UI/UX 디자인' },
    { id: 87, name: '모바일 앱 디자인' },
    { id: 88, name: '웹디자인' },
    { id: 89, name: '패키지 디자인' },
    { id: 90, name: '이모티콘 디자인' },
    { id: 91, name: 'BI/CI 디자인' },
  ],
  6: [
    { id: 92, name: '카피라이팅' },
    { id: 93, name: '콘텐츠 라이팅' },
    { id: 94, name: '기사작성' },
    { id: 95, name: '보고서 작성' },
    { id: 96, name: '제안서 작성' },
    { id: 97, name: '브랜드 네이밍' },
    { id: 98, name: '슬로건 제작' },
    { id: 99, name: '웹소설' },
    { id: 100, name: '시나리오' },
    { id: 101, name: '논문작성' },
    { id: 102, name: '사용자 매뉴얼 작성' },
    { id: 103, name: '블로그 포스팅' },
    { id: 104, name: '홍보문 작성' },
    { id: 105, name: '에세이 대필' },
    { id: 106, name: '이메일 작성' },
  ],
  7: [
    { id: 107, name: '영어 번역' },
    { id: 108, name: '중국어 번역' },
    { id: 109, name: '일본어 번역' },
    { id: 110, name: '독일어 번역' },
    { id: 111, name: '프랑스어 번역' },
    { id: 112, name: '동시통역' },
    { id: 113, name: '순차통역' },
    { id: 114, name: '문서번역' },
    { id: 115, name: '의료번역' },
    { id: 116, name: '기술번역' },
    { id: 117, name: '법률 번역' },
    { id: 118, name: '자막 번역' },
    { id: 119, name: '영상번역' },
    { id: 120, name: '게임 번역' },
    { id: 121, name: '통역 가이드' },
  ],
  8: [
    { id: 122, name: '상품사진' },
    { id: 123, name: '인물사진' },
    { id: 124, name: '웨딩사진' },
    { id: 125, name: '브랜딩 사진' },
    { id: 126, name: '행사사진' },
    { id: 127, name: '홍보영상' },
    { id: 128, name: '유튜브 영상' },
    { id: 129, name: '애니메이션' },
    { id: 130, name: '모션그래픽' },
    { id: 131, name: '영상편집' },
    { id: 132, name: 'Vlog 제작' },
    { id: 133, name: '쇼츠 편집' },
    { id: 134, name: '인터뷰 영상' },
    { id: 135, name: '뮤직비디오 제작' },
    { id: 136, name: '드론 촬영' },
  ],
  9: [
    { id: 137, name: '온라인 강의' },
    { id: 138, name: '기업교육' },
    { id: 139, name: '1:1 과외' },
    { id: 140, name: '그룹 수업' },
    { id: 141, name: '워크샵' },
    { id: 142, name: '세미나 진행' },
    { id: 143, name: 'e-러닝 콘텐츠' },
    { id: 144, name: '교육과정 개발' },
    { id: 145, name: '강의자료 제작' },
    { id: 146, name: '시험출제' },
    { id: 147, name: '멘토링 프로그램 기획' },
    { id: 148, name: '문해력 교육' },
    { id: 149, name: '디지털 리터러시' },
    { id: 150, name: '교수법 컨설팅' },
    { id: 151, name: '강사 코칭' },
  ],
  10: [
    { id: 152, name: '맞춤 가구' },
    { id: 153, name: '인테리어 소품' },
    { id: 154, name: '액세서리 제작' },
    { id: 155, name: '의류 제작' },
    { id: 156, name: '가방 제작' },
    { id: 157, name: '케이크 제작' },
    { id: 158, name: '꽃다발' },
    { id: 159, name: '캘리그라피' },
    { id: 160, name: '일러스트 제작' },
    { id: 161, name: '캐릭터 디자인' },
    { id: 162, name: '핸드메이드 촛불' },
    { id: 163, name: '비누 제작' },
    { id: 164, name: '타로 카드 디자인' },
    { id: 165, name: '폰케이스 제작' },
    { id: 166, name: '나만의 향수 제작' },
  ],
  11: [
    { id: 167, name: '피아노' },
    { id: 168, name: '기타' },
    { id: 169, name: '드럼' },
    { id: 170, name: '보컬' },
    { id: 171, name: '댄스' },
    { id: 172, name: '요가' },
    { id: 173, name: '필라테스' },
    { id: 174, name: '그림 그리기' },
    { id: 175, name: '서예' },
    { id: 176, name: '요리' },
    { id: 177, name: '베이킹' },
    { id: 178, name: '플라워 클래스' },
    { id: 179, name: '캘리그라피 레슨' },
    { id: 180, name: '사진 입문' },
    { id: 181, name: '디지털 드로잉' },
  ],
  12: [
    { id: 182, name: '청소 서비스' },
    { id: 183, name: '정리정돈' },
    { id: 184, name: '펜트하우스 관리' },
    { id: 185, name: '반려동물 돌봄' },
    { id: 186, name: '식물 관리' },
    { id: 187, name: '운전대행' },
    { id: 188, name: '심부름' },
    { id: 189, name: '이사 도움' },
    { id: 190, name: '가사도우미' },
    { id: 191, name: '육아도우미' },
    { id: 192, name: '정수기 필터 교체' },
    { id: 193, name: '가전제품 수리' },
    { id: 194, name: '세탁 대행' },
    { id: 195, name: '홈케어 서비스' },
    { id: 196, name: '실버케어 서비스' },
  ],
} as const;
