name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - deploy

env:
  NODE_VERSION: '20'
  S3_BUCKET_NAME: 'jamx2.kro.kr'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run type check
        run: yarn tsc --noEmit

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: production
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_PORTONE_CHANNEL_KEY: ${{ secrets.VITE_PORTONE_CHANNEL_KEY }}
          VITE_PORTONE_STORE_ID: ${{ secrets.VITE_PORTONE_STORE_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ env.S3_BUCKET_NAME }} --delete --cache-control "public, max-age=31536000" --exclude "*.html"
          aws s3 sync ./dist s3://${{ env.S3_BUCKET_NAME }} --delete --cache-control "public, max-age=0, must-revalidate" --include "*.html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
            --paths "/*"
